security:
    encoders:
        App\Entity\User: bcrypt

    providers:
        app_provider:
            entity:
                class: App\Entity\User
                property: email

    role_hierarchy:
        ROLE_ADMIN: ROLE_MANAGER
        ROLE_MANAGER: ROLE_USER

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true
            provider: app_provider
            form_login:
                login_path: user_login
                check_path: user_login
                default_target_path: event_create
            logout:
                path: user_logout
                target: event_list

    access_control:
         - { path: ^/admin, roles: ROLE_MANAGER }
